service:
  database:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "postgres"
    sslMode : "disable"
    dbname: "postgres"
    poolMaxConns: 2
  token:
    TOKEN_EXPIRED_IN: 60m
    TOKEN_MAXAGE: 60
    TOKEN_SECRET: my-ultra-secure-json-web-token-string
  email:  
    EMAIL_FROM: admin@admin.com
    SMTP_HOST: sandbox.smtp.mailtrap.io
    SMTP_USER: 945aae80408a57
    SMTP_PASS: 81a06053f55d6b
    SMTP_PORT: 2525
  
  